version: "3.1"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "2000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: pbid
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db_files:/data/db

  api:
    image: "node:lts-alpine"
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - "2001:3000"
    command: npm run dev
    depends_on:
      - db

  app:
    image: "node:lts-alpine"
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "2002:3000"
    command: npm run dev
    depends_on:
      - db
      - api

volumes:
  db_files: {}
